### ISSUE TITLE
Don't re-run func tests on each approval.

### ISSUE THREAD

**Issue by mkalcok** [canonical/bootstack-actions#19]
I observed that currently each `approve` in the PR triggers a new run of functional tests even if there are no changes since last approval. I'm not sure if it's possible but it'd be nice if func tests ran only on first "approval" or if there were changes since last approval.

Current flow:

- PR is created
- First reviewer gives approval
- Functional tests run
- Second reviewer gives approval
- **Functional tests run again**
- PR is ready for merge

Desired flow:

- PR is created
- First reviewer gives approval
- Functional tests run
- Second reviewer gives approval
- PR is ready for merge

Of course if there are additional changes made to the PR, func test should be re-ran:

- PR is created
- First reviewer gives approval
- Functional tests run
- **Changes are pushed to the PR**
- Second reviewer gives approval
- **Functional tests run again**
- PR is ready for merge

**Comment by Pjack** [comment]
@agileshaw Is there any sample that we run func test many times without any new commit?
I am a little surprised that the func test will be triggered by "Second reviewer gives approval". From the [code](https://github.com/canonical/bootstack-actions/blob/main/.github/workflows/test-func.yaml) the behavior doesn't look like this. 

I even suspect that we only need to adjust the events then we can avoid unnessary functional tes

**Comment by agileshaw** [comment]
@Pjack Yes. Taking [PR #45 ](https://github.com/canonical/prometheus-juju-exporter/pull/45) of prometheus-juju-exporter as an example, workflow run [#87](https://github.com/canonical/prometheus-juju-exporter/actions/runs/4800738842) and [#89](https://github.com/canonical/prometheus-juju-exporter/actions/runs/4804904185) are triggered by opening and updating PR, whereas [#90](https://github.com/canonical/prometheus-juju-exporter/actions/runs/4805712383) and [#91](https://github.com/canonical/prometheus-juju-exporter/actions/runs/4809770622) are triggered by Robert's and my approval.

Here is the [condition code](https://github.com/canonical/bootstack-actions/blob/main/.github/workflows/pull-request.yaml#L82) triggering workflows on approval. And the link you shared is for testing inside bootstack-action, not the actual workflow used by other repos.
