### ISSUE TITLE
Allow option to choose if we want to set up Juju environment or not

### ISSUE THREAD

**Issue by chanchiwai-ray** [canonical/bootstack-actions#28]
The workflow for pull request assumes that we need Juju environment to run `func` job, but it is not always the case. For example, a snap project will not likely need Juju environment, setting it up will only waste time and resource.

**Comment by agileshaw** [comment]
Good idea. Like `snapcraft`, we should have an input variable to allow projects to determine whether setting up juju is necessary.

**Comment by Pjack** [comment]
available in v3
