### ISSUE TITLE
Adding `recheck` keyword for triggering workflow

### ISSUE THREAD

**Issue by agileshaw** [canonical/bootstack-actions#37]
For PRs opened by bot, workflows will not be triggered automatically. At the moment we are closing and re-opening the PR to manually trigger workflows (e.g. https://github.com/canonical/snap-tempest/pull/55), It would be much easier and intuitive if we can simply submit a `recheck` review comment to trigger the workflow.

**Comment by aieri** [comment]
as we've decided to move away from bootstack-actions we don't plan to implement this, sorry
